### ISSUE TITLE
Remover chamadas var_dump

### ISSUE THREAD

**Issue by hussani** [rogeriopradoj/php-translation-fest-digital-ocean-email-voucher#1]
Remover do index.php as chamadas var_dump usadas no debug em dev.

**Comment by rogeriopradoj** [comment]
PR, please!!!

**Comment by hussani** [comment]
Estava no celular quando abri a issue.
Um momento que já mando um PR

**Comment by malukenho** [comment]
@rogeriopradoj can be closed.

**Comment by rogeriopradoj** [comment]
Thanks @malukenho!
